---
- hosts: web
  become: yes
  tasks:
    - name: download zabbix-agent
      get_url:
        url: https://repo.zabbix.com/zabbix/6.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.2-4%2Bubuntu20.04_all.deb
        dest: /tmp/zabbix-release_6.2-4+ubuntu20.04_all.deb
    - name: install zabbix-agent
      shell: dpkg -i /tmp/zabbix-release_6.2-4+ubuntu20.04_all.deb
#|| yes | find /packages/apt/ -type f -name "*.deb" -exec dpkg --force-depends -i {} \+
    - name: Add repository
      apt_repository:
        repo: 'deb https://repo.zabbix.com/zabbix/6.2/ubuntu focal main'
        state: present
        filename: 'zabbix'
    - name: Add deb-src line to apt sources
      become: true
      lineinfile:
        path: /etc/apt/sources.list.d/zabbix.list
        line: 'deb-src https://repo.zabbix.com/zabbix/6.2/ubuntu focal main'
        state: present
    - name : Update all packages
      apt:
        name="*"
        force_apt_get=true
        state=latest
        update_cache=true
#    - name: Update apt repo and cache on all Debian/Ubuntu boxes
#      apt: upgrade=dist force_apt_get=yes
#        update_cache: yes
#        force_apt_get: yes
#        cache_valid_time: 3600
    - name: install zabbix-agent
      apt:
        name: zabbix-agent
        state: latest
#        update_cache: yes
#        dpkg_options: 'force-overwrite,force-confnew'
    - name: config zabbix-agent
      template:
        src: /etc/ansible/templates/zabbix_agentd.conf.t
        dest: /etc/zabbix/zabbix_agentd.conf
        owner: root
        group: root
        mode: 0644
    - name: start and enable service zabbix-agent
      ansible.builtin.service:
        name: zabbix-agent
        state: started
        enabled: yes
    - name: Restart service zabbix-agent
      ansible.builtin.service:
        name: zabbix-agent
        state: restarted
